name: Calculate & update repo size
on:
  workflow_dispatch:
jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure Git
        uses: iniyatig/actions-example/.github/actions/configure-git@main

      - name: Verify Git Config
        run: |
          git config --list
