name: Calculate & update repo size
on:
  workflow_dispatch:
jobs:
  calc-update-repo-size:
    name: Calculate and update repository size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure git
        uses: iniyatig/actions-example/.github/actions@main
