name: Check File Permissions

on:
  workflow_dispatch  # allows you to trigger manually

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List file permissions
        run: |
          chmod +x .github/actions/git-configure.sh
          ls -l .github/actions/git-configure.sh
          git status
